### ISSUE TITLE
Missing crownstone_core.packets.debug

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-lib-python-ble#1]
When running `python3 ./examples/example_continuous_scanning.py`, there's the following error:

```
Traceback (most recent call last):
  File "./examples/example_continuous_scanning.py", line 10, in <module>
    from crownstone_ble import CrownstoneBle
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/crownstone_ble-0.5.3-py3.8.egg/crownstone_ble/__init__.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/crownstone_ble-0.5.3-py3.8.egg/crownstone_ble/core/CrownstoneBle.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/crownstone_ble-0.5.3-py3.8.egg/crownstone_ble/core/ble_modules/DebugHandler.py", line 17, in <module>
ModuleNotFoundError: No module named 'crownstone_core.packets.debug'
```

**Comment by mrquincle** [comment]
Clone https://github.com/crownstone/crownstone-lib-python-core and install.

**Comment by AlexDM0** [comment]
Actually, it'd be better to run 
```
pip3 install -r requirements.txt 
```

This could be added to the readme too.

Ideally you install the module itself via pip, which should take care of this for you.
