### ISSUE TITLE
Missing bluepy-helper

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-lib-python-ble#2]
When running `python3 ./examples/example_continuous_scanning.py`, there's the following error:

```
We're loading some default encryption keys into the library: "adminKeyForCrown", "memberKeyForHome", "basicKeyForOther", "MyServiceDataKey", "aLocalizationKey", "MyGoodMeshAppKey", "MyGoodMeshNetKey".

Scanning for Crownstones..
Traceback (most recent call last):
  File "./examples/example_continuous_scanning.py", line 29, in <module>
    core.startScanning(60)
  File "/usr/local/lib/python3.8/dist-packages/crownstone_ble-0.5.3-py3.8.egg/crownstone_ble/core/CrownstoneBle.py", line 84, in startScanning
  File "/usr/local/lib/python3.8/dist-packages/crownstone_ble-0.5.3-py3.8.egg/crownstone_ble/core/ble_modules/BleHandler.py", line 89, in startScanning
  File "/usr/local/lib/python3.8/dist-packages/bluepy-1.3.0-py3.8.egg/bluepy/btle.py", line 789, in start
    self._startHelper(iface=self.iface)
  File "/usr/local/lib/python3.8/dist-packages/bluepy-1.3.0-py3.8.egg/bluepy/btle.py", line 279, in _startHelper
    self._helper = subprocess.Popen(args,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/bluepy-1.3.0-py3.8.egg/bluepy/bluepy-helper
```

**Comment by mrquincle** [comment]
This is an issue that has been seen before. It stems from the fact that `make` did not run after install `bluepy`, see https://github.com/IanHarvey/bluepy/issues/158.

**Comment by mrquincle** [comment]
Manually reinstall `bluepy` with something like `pip3 install --upgrade --force-reinstall bluepy`.

**Comment by mrquincle** [comment]
If it still doesn't work just run `make` manually in the given directory and blame the package providers and the myriad of ways python can exist on your system.
