### ISSUE TITLE
Permission denied on 'le on'

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-lib-python-ble#3]
When running `/examples/example_continuous_scanning.py`

```
We're loading some default encryption keys into the library: "adminKeyForCrown", "memberKeyForHome", "basicKeyForOther", "MyServiceDataKey", "aLocalizationKey", "MyGoodMeshAppKey", "MyGoodMeshNetKey".

Scanning for Crownstones..
Traceback (most recent call last):
  File "./examples/example_continuous_scanning.py", line 29, in <module>
    core.startScanning(60)
  File "/usr/local/lib/python3.8/dist-packages/crownstone_ble-0.5.3-py3.8.egg/crownstone_ble/core/CrownstoneBle.py", line 84, in startScanning
  File "/usr/local/lib/python3.8/dist-packages/crownstone_ble-0.5.3-py3.8.egg/crownstone_ble/core/ble_modules/BleHandler.py", line 89, in startScanning
  File "/home/anne/.local/lib/python3.8/site-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/home/anne/.local/lib/python3.8/site-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
```

**Comment by mrquincle** [comment]
As described in the README, use `sudo` or set the given scan permissions explicitly via `setcap`.
